from __future__ import annotations

import json
import os
import threading
import tkinter as tk
from pathlib import Path
from tkinter import messagebox, ttk

from windows_certification_agent import (
    DEFAULT_BACKEND_URL,
    DEFAULT_DASHBOARD_URL,
    collect_report,
    upload_report,
)


REPORT_PATH = Path.home() / "Documents" / "LMX-Windows-Certification" / "windows_certification_report.json"


class WindowsCertificationApp:
    def __init__(self) -> None:
        self.backend_url = os.environ.get("LMX_BACKEND_URL", DEFAULT_BACKEND_URL)
        self.report: dict | None = None

        self.root = tk.Tk()
        self.root.title("LMX Windows Certification")
        self.root.geometry("500x350")
        self.root.minsize(500, 350)
        self.root.maxsize(600, 400)
        self.root.configure(bg="#F8FAFC")

        self.status_text = tk.StringVar(value="Ready")
        self.lmx_text = tk.StringVar(value="LMX Detected: -")
        self.result_text = tk.StringVar(value="Certification Result: -")
        self.score_text = tk.StringVar(value="Score: -")

        self._build_ui()

    def run(self) -> None:
        self.root.mainloop()

    def _build_ui(self) -> None:
        style = ttk.Style()
        style.theme_use("clam")
        style.configure("TFrame", background="#F8FAFC")
        style.configure("Card.TFrame", background="#FFFFFF", relief="flat")
        style.configure("Title.TLabel", background="#F8FAFC", foreground="#0F172A", font=("Segoe UI", 17, "bold"))
        style.configure("Subtitle.TLabel", background="#F8FAFC", foreground="#475569", font=("Segoe UI", 8))
        style.configure("Status.TLabel", background="#FFFFFF", foreground="#2563EB", font=("Segoe UI", 12, "bold"))
        style.configure("Body.TLabel", background="#FFFFFF", foreground="#0F172A", font=("Segoe UI", 10))
        style.configure("Primary.TButton", font=("Segoe UI", 9, "bold"), padding=(10, 7))
        style.configure("TButton", font=("Segoe UI", 9), padding=(10, 7))

        main = ttk.Frame(self.root, padding=18)
        main.pack(fill="both", expand=True)

        ttk.Label(main, text="LMX Windows Certification", style="Title.TLabel").pack(anchor="w")
        ttk.Label(main, text="Generated by LMX Device Certification Platform", style="Subtitle.TLabel").pack(anchor="w", pady=(2, 12))

        status_card = ttk.Frame(main, style="Card.TFrame", padding=14)
        status_card.pack(fill="x", pady=(0, 12))
        ttk.Label(status_card, textvariable=self.status_text, style="Status.TLabel").pack(anchor="w", pady=(0, 8))
        ttk.Label(status_card, textvariable=self.lmx_text, style="Body.TLabel").pack(anchor="w", pady=2)
        ttk.Label(status_card, textvariable=self.result_text, style="Body.TLabel").pack(anchor="w", pady=2)
        ttk.Label(status_card, textvariable=self.score_text, style="Body.TLabel").pack(anchor="w", pady=2)

        buttons = ttk.Frame(main)
        buttons.pack(fill="x", pady=(0, 10))
        buttons.columnconfigure((0, 1, 2), weight=1, uniform="actions")
        ttk.Button(buttons, text="Run Certification", style="Primary.TButton", command=self.run_certification).grid(row=0, column=0, sticky="ew", padx=(0, 6))
        ttk.Button(buttons, text="Upload Report", command=self.upload_current_report).grid(row=0, column=1, sticky="ew", padx=3)
        ttk.Button(buttons, text="Exit", command=self.root.destroy).grid(row=0, column=2, sticky="ew", padx=(6, 0))

        footer = ttk.Label(
            main,
            text=f"Dashboard: {DEFAULT_DASHBOARD_URL}",
            style="Subtitle.TLabel",
            wraplength=440,
        )
        footer.pack(anchor="w", side="bottom")

    def run_certification(self) -> None:
        self.status_text.set("Running certification...")
        threading.Thread(target=self._run_certification_worker, daemon=True).start()

    def _run_certification_worker(self) -> None:
        try:
            report = collect_report()
            self._write_report(report)
            self.report = report
            self.root.after(0, lambda: self._show_report(report))
        except Exception as error:
            self.root.after(0, lambda: self._show_error(f"Certification failed: {error}"))

    def upload_current_report(self) -> None:
        if not self.report:
            self.report = self._read_saved_report()
        if not self.report:
            messagebox.showwarning("No Report", "Run Certification before uploading.")
            return
        self.status_text.set("Uploading...")
        threading.Thread(target=self._upload_worker, daemon=True).start()

    def _upload_worker(self) -> None:
        try:
            status, body = upload_report(self.backend_url, self.report or {})
            if 200 <= status < 300:
                self.root.after(0, self._show_upload_success)
            else:
                self.root.after(0, lambda: self._show_error(f"Upload failed: HTTP {status}\n{body}"))
        except Exception as error:
            self.root.after(0, lambda: self._show_error(f"Upload failed: {error}"))

    def _show_report(self, report: dict) -> None:
        lmx_detected = "YES" if report.get("lmx_app_installed") else "NO"
        self.status_text.set("Certification Complete")
        self.lmx_text.set(f"LMX Detected: {lmx_detected}")
        self.result_text.set(f"Certification Result: {report.get('final_status', '-')}")
        self.score_text.set(f"Score: {report.get('score', '-')} / 100")

    def _show_upload_success(self) -> None:
        self.status_text.set("Upload Successful")
        messagebox.showinfo(
            "Upload Successful",
            f"Report uploaded successfully.\n\nView results on:\n{DEFAULT_DASHBOARD_URL}",
        )

    def _show_error(self, message: str) -> None:
        self.status_text.set("Upload Failed" if message.startswith("Upload") else "Certification Failed")
        messagebox.showerror("LMX Windows Certification", message)

    def _write_report(self, report: dict) -> None:
        REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
        REPORT_PATH.write_text(json.dumps(report, indent=2), encoding="utf-8")

    def _read_saved_report(self) -> dict | None:
        try:
            return json.loads(REPORT_PATH.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return None


def main() -> int:
    WindowsCertificationApp().run()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
