from __future__ import annotations

import json
import os
import sys
import threading
from pathlib import Path
from tkinter import messagebox

try:
    import customtkinter as ctk
except Exception:  # pragma: no cover - fallback only when dependency is unavailable
    ctk = None
    import tkinter as tk
    from tkinter import ttk

from windows_certification_agent import (
    DEFAULT_BACKEND_URL,
    DEFAULT_DASHBOARD_URL,
    collect_report,
    upload_report,
)


REPORT_FILENAME = "windows_certification_report.json"
CHECK_LABELS = {
    "windows_os": "Operating System",
    "cpu": "CPU",
    "ram": "RAM",
    "storage": "Storage",
    "gpu": "GPU",
    "network": "Network",
    "time_timezone": "Time / Timezone",
    "lmx_app_installed": "LMX Installed",
    "lmx_version": "LMX Version",
    "lmx_app_launch": "LMX Launch",
    "pull_to_content": "Pull To Content",
}
READINESS_LABELS = {
    "auto_login": "Auto Login",
    "auto_startup": "Auto Startup",
    "power_settings": "Power Settings",
    "display_scaling": "Display Scaling",
    "wake_timers": "Wake Timers",
    "windows_update_status": "Windows Update Status",
}


class WindowsCertificationApp:
    def __init__(self) -> None:
        self.backend_url = os.environ.get("LMX_BACKEND_URL", DEFAULT_BACKEND_URL)
        self.report: dict | None = None
        self.report_path: Path | None = None

        if ctk:
            ctk.set_appearance_mode("light")
            ctk.set_default_color_theme("blue")
            self.root = ctk.CTk()
            self._build_customtk()
        else:
            self.root = tk.Tk()
            self._build_tk()

    def run(self) -> None:
        self.root.mainloop()

    def _build_customtk(self) -> None:
        self.root.title("LMX Windows Certification")
        self.root.geometry("980x760")
        self.root.minsize(900, 680)

        self.status_text = ctk.StringVar(value="Ready")

        header = ctk.CTkFrame(self.root, fg_color="#FFFFFF", corner_radius=14)
        header.pack(fill="x", padx=18, pady=(18, 8))
        ctk.CTkLabel(header, text="LMX Windows Certification", font=("Segoe UI", 28, "bold"), text_color="#0F172A").pack(anchor="w", padx=18, pady=(16, 2))
        ctk.CTkLabel(header, text="Device Certification & Deployment Readiness", font=("Segoe UI", 15), text_color="#475569").pack(anchor="w", padx=18)
        ctk.CTkLabel(header, text="Generated by LMX Device Certification Platform", font=("Segoe UI", 12), text_color="#64748B").pack(anchor="w", padx=18, pady=(4, 16))

        actions = ctk.CTkFrame(self.root, fg_color="#FFFFFF", corner_radius=14)
        actions.pack(fill="x", padx=18, pady=(0, 8))
        for text, command, color in [
            ("Run Certification", self.run_certification, "#2563EB"),
            ("Upload Report", self.upload_current_report, "#16A34A"),
            ("Show Backend URL", self.show_backend_url, "#334155"),
            ("Exit", self.root.destroy, "#64748B"),
        ]:
            ctk.CTkButton(actions, text=text, command=command, fg_color=color, hover_color=color, height=38).pack(side="left", padx=10, pady=14)
        ctk.CTkLabel(actions, textvariable=self.status_text, text_color="#475569").pack(side="right", padx=14)

        self.content = ctk.CTkScrollableFrame(self.root, fg_color="#F8FAFC")
        self.content.pack(fill="both", expand=True)

        self.summary_frame = self._card("Result Summary")
        self.device_frame = self._card("Device Information")
        self.check_frame = self._card("Compatibility Checks")
        self.readiness_frame = self._card("Deployment Readiness")
        self.report_frame = self._card("Report Summary")
        self._show_placeholder()

    def _build_tk(self) -> None:
        self.root.title("LMX Windows Certification")
        self.root.geometry("980x760")
        self.status_text = tk.StringVar(value="Ready")
        header = ttk.Frame(self.root, padding=16)
        header.pack(fill="x")
        ttk.Label(header, text="LMX Windows Certification", font=("Segoe UI", 24, "bold")).pack(anchor="w")
        ttk.Label(header, text="Device Certification & Deployment Readiness").pack(anchor="w")
        ttk.Label(header, text="Generated by LMX Device Certification Platform").pack(anchor="w", pady=(0, 12))
        actions = ttk.Frame(self.root, padding=(16, 0, 16, 8))
        actions.pack(fill="x")
        for text, command in [
            ("Run Certification", self.run_certification),
            ("Upload Report", self.upload_current_report),
            ("Show Backend URL", self.show_backend_url),
            ("Exit", self.root.destroy),
        ]:
            ttk.Button(actions, text=text, command=command).pack(side="left", padx=4)
        ttk.Label(actions, textvariable=self.status_text).pack(side="right")
        self.content = ttk.Frame(self.root, padding=16)
        self.content.pack(fill="both", expand=True)
        self.summary_frame = self._card("Result Summary")
        self.device_frame = self._card("Device Information")
        self.check_frame = self._card("Compatibility Checks")
        self.readiness_frame = self._card("Deployment Readiness")
        self.report_frame = self._card("Report Summary")
        self._show_placeholder()

    def _card(self, title: str):
        frame = ctk.CTkFrame(self.content, fg_color="#FFFFFF", corner_radius=14) if ctk else ttk.LabelFrame(self.content, text=title, padding=12)
        frame.pack(fill="x", padx=18 if ctk else 0, pady=8)
        if ctk:
            ctk.CTkLabel(frame, text=title, font=("Segoe UI", 17, "bold"), text_color="#0F172A").pack(anchor="w", padx=16, pady=(12, 6))
        return frame

    def run_certification(self) -> None:
        self.status_text.set("Running certification...")
        threading.Thread(target=self._run_certification_worker, daemon=True).start()

    def _run_certification_worker(self) -> None:
        try:
            report = collect_report()
            path = self._write_report(report)
            self.report = report
            self.report_path = path
            self.root.after(0, lambda: self._render_report(report, f"Certification complete. Saved to {path}"))
        except Exception as error:
            self.root.after(0, lambda: self._set_error(f"Certification failed: {error}"))

    def upload_current_report(self) -> None:
        if not self.report:
            messagebox.showwarning("No Report", "Run Certification before uploading.")
            return
        self.status_text.set("Uploading...")
        threading.Thread(target=self._upload_worker, daemon=True).start()

    def _upload_worker(self) -> None:
        try:
            status, body = upload_report(self.backend_url, self.report or {})
            if 200 <= status < 300:
                message = f"Report uploaded successfully.\nPlease refresh the dashboard.\n\nDashboard URL:\n{DEFAULT_DASHBOARD_URL}"
                self.root.after(0, lambda: self._upload_success(message))
            else:
                self.root.after(0, lambda: self._set_error(f"Upload failed: HTTP {status}\n{body}"))
        except Exception as error:
            self.root.after(0, lambda: self._set_error(f"Upload failed: {error}"))

    def show_backend_url(self) -> None:
        messagebox.showinfo("Backend URL", self.backend_url)

    def _upload_success(self, message: str) -> None:
        self.status_text.set("Upload Successful")
        messagebox.showinfo("Upload Successful", message)

    def _set_error(self, message: str) -> None:
        self.status_text.set(message)
        messagebox.showerror("LMX Windows Certification", message)

    def _write_report(self, report: dict) -> Path:
        candidates = [
            self._app_dir() / REPORT_FILENAME,
            Path.home() / "Documents" / "LMX-Windows-Certification" / REPORT_FILENAME,
        ]
        for path in candidates:
            try:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(json.dumps(report, indent=2), encoding="utf-8")
                return path
            except OSError:
                continue
        raise OSError("Unable to save report file.")

    def _app_dir(self) -> Path:
        if getattr(sys, "frozen", False):
            return Path(sys.executable).resolve().parent
        return Path(__file__).resolve().parent

    def _render_report(self, report: dict, status: str) -> None:
        self.status_text.set(status)
        self._clear_cards()
        self._rows(self.summary_frame, [
            ("Device Certification", report.get("final_status", "-")),
            ("Certification Score", f"{report.get('score', '-')} / 100"),
            ("Final Recommendation", report.get("final_recommendation", "-")),
        ])
        self._rows(self.device_frame, [
            ("Computer Name", report.get("computer_name")),
            ("Manufacturer", report.get("manufacturer")),
            ("Model", report.get("model")),
            ("Windows Version", report.get("windows_edition") or report.get("windows_version")),
            ("Windows Build", report.get("windows_build_number")),
            ("CPU", report.get("cpu")),
            ("RAM", f"{report.get('ram_total_gb', '-')} GB"),
            ("Storage Available", f"{report.get('storage_available_gb', '-')} GB"),
            ("GPU", report.get("gpu")),
            ("Screen Resolution", report.get("screen_resolution")),
            ("Timezone", report.get("timezone")),
            ("LMX Version", report.get("lmx_app_version") or "LMX Content is not installed."),
        ])
        self._status_rows(self.check_frame, CHECK_LABELS, report.get("checks", {}))
        self._status_rows(self.readiness_frame, READINESS_LABELS, report.get("deployment_readiness", {}))
        summary = report.get("device_report_summary", {})
        self._rows(self.report_frame, [
            ("Overall Summary", summary.get("overall_summary")),
            ("Strengths", self._join(summary.get("good_points"))),
            ("Warnings", self._join(summary.get("warning_points"))),
            ("Problems", self._join(summary.get("failed_points"))),
            ("Recommended Actions", self._join(summary.get("recommended_actions"))),
        ])

    def _show_placeholder(self) -> None:
        self._rows(self.summary_frame, [("Status", "Click Run Certification to begin.")])

    def _clear_cards(self) -> None:
        for frame in [self.summary_frame, self.device_frame, self.check_frame, self.readiness_frame, self.report_frame]:
            for child in frame.winfo_children()[1 if ctk else 0:]:
                child.destroy()

    def _rows(self, frame, rows: list[tuple[str, object]]) -> None:
        for label, value in rows:
            text = f"{label}: {value or '-'}"
            widget = ctk.CTkLabel(frame, text=text, anchor="w", justify="left", text_color="#0F172A") if ctk else ttk.Label(frame, text=text, wraplength=880)
            widget.pack(anchor="w", padx=16 if ctk else 0, pady=2)

    def _status_rows(self, frame, labels: dict[str, str], checks: dict) -> None:
        for key, label in labels.items():
            item = checks.get(key, {})
            status = item.get("status", "UNKNOWN") if isinstance(item, dict) else str(item or "UNKNOWN")
            message = item.get("message", "") if isinstance(item, dict) else ""
            self._rows(frame, [(label, f"{status} - {message}".strip(" -"))])

    def _join(self, items) -> str:
        if not items:
            return "-"
        return "; ".join(str(item) for item in items)


def main() -> int:
    WindowsCertificationApp().run()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
