from __future__ import annotations

from io import BytesIO
from typing import Any

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)


FOOTER_LINE_1 = "Generated by LMX Device Certification Platform"

CHECK_LABELS = {
    "android_version": "Android Version",
    "ram": "RAM",
    "storage": "Available Storage",
    "webview": "WebView Version",
    "network": "Network Connectivity",
    "time_timezone": "Time / Timezone",
    "lmx_app_installed": "LMX App Installed",
    "lmx_app_launch": "LMX App Launch",
    "lmx_version": "LMX Version",
    "programmatic_vast": "Programmatic / VAST Readiness",
    "pull_to_content": "Pull To Content Readiness",
}

CHECK_ORDER = [
    "android_version",
    "ram",
    "storage",
    "webview",
    "network",
    "time_timezone",
    "lmx_app_installed",
    "lmx_app_launch",
    "lmx_version",
    "programmatic_vast",
    "pull_to_content",
]


def build_pdf_report(context: dict[str, Any]) -> bytes:
    buffer = BytesIO()
    doc = NumberedDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=24 * mm,
        pageCompression=0,
    )
    styles = _pdf_styles()
    story: list[Any] = []

    story.append(Paragraph("LMX Content Device Certification Report", styles["Title"]))
    story.append(Paragraph("Generated by LMX Device Certification Platform", styles["Subtitle"]))
    story.append(Spacer(1, 8 * mm))

    _pdf_section(story, styles, "1. Device Information", _device_info_table(context, styles))
    _pdf_section(story, styles, "2. Certification Result", _certification_table(context, styles))
    _pdf_section(story, styles, "3. Device Compatibility Assessment", _assessment_table(context, styles))
    _pdf_section(story, styles, "4. Device Report Summary", _summary_flowables(context, styles))
    _pdf_section(story, styles, "5. Certification Conclusion", [
        Paragraph(_conclusion(context["final_status"]), styles["Body"])
    ])

    doc.build(story, canvasmaker=FooterCanvas)
    return buffer.getvalue()


def build_docx_report(context: dict[str, Any]) -> bytes:
    document = Document()
    section = document.sections[0]
    section.top_margin = Inches(0.7)
    section.bottom_margin = Inches(0.7)
    section.left_margin = Inches(0.7)
    section.right_margin = Inches(0.7)

    title = document.add_heading("LMX Content Device Certification Report", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle = document.add_paragraph("Generated by LMX Device Certification Platform")
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

    document.add_heading("Device Information", level=1)
    _docx_key_value_table(document, _device_info_rows(context))

    document.add_heading("Certification Result", level=1)
    _docx_key_value_table(document, [
        ("Device Certification Result", context["final_status"]),
        ("Final Recommendation", context["final_recommendation"]),
        ("Certification Score", f"{context['score']} / 100 ({context['score_label']})"),
    ])

    document.add_heading("Device Compatibility Assessment", level=1)
    table = document.add_table(rows=1, cols=3)
    table.style = "Table Grid"
    headers = table.rows[0].cells
    headers[0].text = "Check"
    headers[1].text = "Result"
    headers[2].text = "Details"
    for label, status, message in _assessment_rows(context):
        row = table.add_row().cells
        row[0].text = label
        row[1].text = status
        row[2].text = message

    document.add_heading("Device Report Summary", level=1)
    _docx_summary_section(document, context["device_report_summary"])

    document.add_heading("Certification Conclusion", level=1)
    document.add_paragraph(_conclusion(context["final_status"]))

    footer = section.footer.paragraphs[0]
    footer.text = FOOTER_LINE_1
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER

    buffer = BytesIO()
    document.save(buffer)
    return buffer.getvalue()


class NumberedDocTemplate(BaseDocTemplate):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        frame = Frame(
            self.leftMargin,
            self.bottomMargin,
            self.width,
            self.height,
            id="normal",
        )
        self.addPageTemplates([PageTemplate(id="all", frames=frame)])


class FooterCanvas(canvas.Canvas):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._saved_page_states: list[dict[str, Any]] = []

    def showPage(self) -> None:
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self) -> None:
        page_count = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._footer(page_count)
            super().showPage()
        super().save()

    def _footer(self, page_count: int) -> None:
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#5B6B78"))
        width, _ = A4
        self.drawCentredString(width / 2, 12 * mm, FOOTER_LINE_1)
        self.drawRightString(width - 18 * mm, 10 * mm, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()


def _pdf_styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "Title": ParagraphStyle(
            "ReportTitle",
            parent=base["Title"],
            fontName="Helvetica-Bold",
            fontSize=20,
            leading=24,
            textColor=colors.HexColor("#172026"),
            alignment=1,
        ),
        "Subtitle": ParagraphStyle(
            "ReportSubtitle",
            parent=base["BodyText"],
            fontSize=10,
            leading=13,
            textColor=colors.HexColor("#5B6B78"),
            alignment=1,
        ),
        "Heading": ParagraphStyle(
            "ReportHeading",
            parent=base["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=15,
            textColor=colors.HexColor("#172026"),
            spaceBefore=10,
            spaceAfter=6,
        ),
        "Body": ParagraphStyle(
            "ReportBody",
            parent=base["BodyText"],
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#172026"),
        ),
    }


def _pdf_section(story: list[Any], styles: dict[str, ParagraphStyle], title: str, items: list[Any] | Any) -> None:
    story.append(Paragraph(title, styles["Heading"]))
    if isinstance(items, list):
        story.extend(items)
    else:
        story.append(items)
    story.append(Spacer(1, 4 * mm))


def _device_info_table(context: dict[str, Any], styles: dict[str, ParagraphStyle]) -> Table:
    return _simple_pdf_table(_device_info_rows(context), styles)


def _certification_table(context: dict[str, Any], styles: dict[str, ParagraphStyle]) -> Table:
    return _simple_pdf_table([
        ("Device Certification Result", context["final_status"]),
        ("Final Recommendation", context["final_recommendation"]),
        ("Certification Score", f"{context['score']} / 100 ({context['score_label']})"),
    ], styles)


def _assessment_table(context: dict[str, Any], styles: dict[str, ParagraphStyle]) -> Table:
    data = [[
        Paragraph("Check", styles["Body"]),
        Paragraph("Result", styles["Body"]),
        Paragraph("Details", styles["Body"]),
    ]]
    for label, status, message in _assessment_rows(context):
        data.append([
            Paragraph(label, styles["Body"]),
            Paragraph(status, styles["Body"]),
            Paragraph(message, styles["Body"]),
        ])
    table = Table(data, colWidths=[48 * mm, 28 * mm, 96 * mm], repeatRows=1)
    table.setStyle(_table_style(header=True))
    return table


def _summary_flowables(context: dict[str, Any], styles: dict[str, ParagraphStyle]) -> list[Any]:
    summary = context["device_report_summary"]
    flowables: list[Any] = [
        Paragraph(f"<b>Overall Summary:</b> {summary.get('overall_summary') or '-'}", styles["Body"])
    ]
    sections = [
        ("Good Points", summary.get("good_points") or []),
        ("Warning Points", summary.get("warning_points") or []),
        ("Problem Points", summary.get("failed_points") or []),
        ("Likely Causes", summary.get("likely_causes") or []),
        ("Recommended Actions", summary.get("recommended_actions") or []),
    ]
    for title, items in sections:
        text = "<br/>".join(_bullet(item) for item in items) if items else "-"
        flowables.append(Spacer(1, 2 * mm))
        flowables.append(Paragraph(f"<b>{title}:</b><br/>{text}", styles["Body"]))
    return flowables


def _simple_pdf_table(rows: list[tuple[str, str]], styles: dict[str, ParagraphStyle]) -> Table:
    data = [[Paragraph(label, styles["Body"]), Paragraph(value or "-", styles["Body"])] for label, value in rows]
    table = Table(data, colWidths=[58 * mm, 114 * mm])
    table.setStyle(_table_style(header=False))
    return table


def _table_style(header: bool) -> TableStyle:
    commands = [
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#DCE3EA")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]
    if header:
        commands.extend([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#172026")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ])
    else:
        commands.append(("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F8FAFC")))
    return TableStyle(commands)


def _device_info_rows(context: dict[str, Any]) -> list[tuple[str, str]]:
    raw = context["raw"]
    return [
        ("Device Name", _value(raw, "device_name")),
        ("Manufacturer", _value(raw, "manufacturer")),
        ("Model", _value(raw, "model")),
        ("Android Version", _value(raw, "os_version")),
        ("CPU Architecture", _value(raw, "cpu_architecture")),
        ("RAM", _gb_value(raw, "ram_total_gb")),
        ("Available Storage", _gb_value(raw, "storage_available_gb")),
        ("Screen Resolution", _value(raw, "screen_resolution")),
        ("WebView Version", _value(raw, "webview_version")),
        ("LMX Content Version", _value(raw, "lmx_app_version")),
        ("Report Date", context["created_at"]),
    ]


def _assessment_rows(context: dict[str, Any]) -> list[tuple[str, str, str]]:
    checks = context["checks"]
    rows: list[tuple[str, str, str]] = []
    for key in CHECK_ORDER:
        check = checks.get(key) or {}
        rows.append((
            CHECK_LABELS[key],
            str(check.get("status") or "UNKNOWN"),
            str(check.get("message") or "-"),
        ))
    return rows


def _docx_key_value_table(document: Document, rows: list[tuple[str, str]]) -> None:
    table = document.add_table(rows=0, cols=2)
    table.style = "Table Grid"
    for label, value in rows:
        row = table.add_row().cells
        row[0].text = label
        row[1].text = value or "-"


def _docx_summary_section(document: Document, summary: dict[str, Any]) -> None:
    document.add_paragraph(f"Overall Summary: {summary.get('overall_summary') or '-'}")
    sections = [
        ("Good Points", summary.get("good_points") or []),
        ("Warning Points", summary.get("warning_points") or []),
        ("Problem Points", summary.get("failed_points") or []),
        ("Likely Causes", summary.get("likely_causes") or []),
        ("Recommended Actions", summary.get("recommended_actions") or []),
    ]
    for title, items in sections:
        document.add_paragraph(title, style="Heading 2")
        if items:
            for item in items:
                document.add_paragraph(item, style="List Bullet")
        else:
            document.add_paragraph("-")


def _conclusion(final_status: str) -> str:
    if final_status == "Approved":
        return "This device meets all LMX Content certification requirements and is suitable for deployment."
    if final_status == "Approved with Limitation":
        return "This device can be used for LMX Content but has one or more limitations that should be reviewed before deployment."
    return "This device does not meet the minimum LMX Content requirements and is not recommended for deployment."


def _bullet(value: str) -> str:
    return f"- {value}"


def _value(raw: dict[str, Any], key: str) -> str:
    value = raw.get(key)
    if value is None or value == "":
        return "-"
    return str(value)


def _gb_value(raw: dict[str, Any], key: str) -> str:
    value = raw.get(key)
    if value is None or value == "":
        return "-"
    return f"{value} GB"
